sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- '10'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: qR37yhy89jWF/tv+0pLlZR+PzuyJsTPdXkOMS1cYkiW7BscLWkJvAigyOmeELV2NIaSucYX+L/Cuh6lyS9AxqM/eQrdll9HWNxz2Fo8C0nT9iR39ynjmYTjil74OkBx9UoDTnrJb6ycbUNkdsI2uobmkUWgvy1D8KDOq7/BRukXg+Xy9bL2UduqjwOk9DyTMcPcitZjmEDqMKE3TvfF7Ug8qHT4o9jttS/y/nqBwVd9HjqSKuclGt9T7K0JC4DHMDuiC6FlTF3aGJRfI5K1Hbkevfy5rhWU0eqsJrkPSQwy1Mllb25/TM3da8J7wjo2UjsR9KbbpDjqLgAOOxj3AOe6AeQPlwg1QyEUBju7Clcl8W5vwFoPdLlDkNfXJfhxIgbmT435WzkGP6Ig/GwjaL4vFaFikqx++2reHT/VXA16+2OEGJZ8O9twV+VFPSB4fDtQ2YtjHyS2VQZ7cph6R0qta1iPedHwTY2H8hCD4XzhV0ZETXBfSq3Ng528W1aAfc6Gcpp9c/ICyRGZpkLqukK1mu9HbTfzZ+tOrP49eJhVdJR7XgqWTr2WO6lq8JMWq8J4dJZDj3xeheMYiDhrzxI/3Wd13uLyL3un461hYMRBfl8whn5/FBnJLlrBuYNjL2jf4XV5qKyKIF7cA9sVwrRQUBrc56jDDG/Z32yL6TLc=
  - secure: K9vxmqEDEThvRR2kBERdgqSnXrn9+i4slBZ+cIPnz0NfUwXT+XgMjhRncrFoN2C6kDuJ867HGNu1lv/WtDbSWwem/bhFld/kf9EgUrKJLwqxcm9cAgdD8vOgooue2JjJYV34WoH9F1Oqo2dDPxMmw97cjFll0gdlANdRp97ww/w9sGhvnuZRC3FBQ5BnXDecE5TdTK8DJxfoOfnEZZuJtrSj8SWEaqdEocBMqurOqH2hHCAn4pgM87a1mmNrFlErMc6QGfySiS+v+nXsfcar5EguQHPPIyKVGG2cGU4qJI5h6sGiNUHqL4vLcRo0uBg0qn4MLh08GMpd1c26tnxUORRq1oVy/J6ARiZPcresnEcbcyRbiwJKvd5cghmhQku38QUQVWruVApLGEDij8D6Sl6+1NR8SMNoOAz9LpNQ09anG5M/EMG3DxUuYUEYAojvXUFqyT64Utgryx2Yn5sX8F7I0PZtRdg5PAymNSaoe9L/PGcEHJhazArqBixLJHzxLH/rRYND4pSfK/sj2rXElI+mm3uXyshisJMwg1+IBVLQswUTsokGwhaplbhqvd8CmcIaY1A1f6E+QBYupe5keBOOrfW/PMqITMJB/x5uVkuo1NyCc27Mhn8bhB7IlCURdBD7OWcEJncROPOn8TMkRUuqUNEAJkFxNw3PLNPbvIo=
  - secure: D4U0ZrQDS59yOV6RFT0aavYDbtiYRbxGdlcpGExXpWTxgh617my1mp5JrHWxfZPsS/ueuQPEE5L0aQ++WEmzIvu6K4jJdBJkyrTd6F962tDBmKKc6Dil68KHvWiEnVM58Y7w+Au8Fl+6+uon5zISe2+MUB1mHBfIAnGWQ6qDTi7uqIjinZORTM6kdfXiy/HpHxb7apDSvEeUkrmGjTBoRT3pLepLFnwX9PDo2FF4XjZvmsH/6DCWzWjzMhlv77gSjp4Uv3gY9TDy1rWDlxwhehx8kjvh06kpXPQzmM21aBq4wee1993WN22Gm17on7XveKoH0sC1cRwtfgsEGiWdXstlr2n2IKdealGj8HlcZwTGk6RbNo7tjxShlS2H4udz1ryoXWd0fekgWP2jmw1gLjrSKQItmuQfghwlppKPY+uM4mTWcm4Zz+ThZ7npe5J9tXB1Iusn32Jp6sO4O6fm6OyKi9T3SYLzms5v+Ib+uKWS8z5sgCEqrEHulq/FenBorroVaNYSW7I7FtZYBNq92Cp06DYrZSkbnCQ8CxKuTA5Eo7bnCVjecClU4dMRijwNnBvzYL94GwuQFmwCWN8/C7MLLw6TRBE43Sn7jumZASipHMgko8V9oMIKveijg6Knpte9jPby2EuBbma7dc7EaFuoI+I98hZw0tXC/9xFQOc=
